# @package _global_

defaults:
  - _self_

model:
  name: google-bert/bert-base-uncased
  top_p: 0.9
  temperature: 0.7
  
primer:
  name: default
  text: ""

prompt:
  system: You are a helpful assitant.
  user: What is AI?

hydra:
  run:
    dir: geobias_logs/run/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: geobias_logs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}

seed: 1
