# @package _global_

defaults:
  - _self_

model:
  name: google-bert/bert-base-uncased
  primer: ""
  primer_name: default
  top_p: 0.9
  temperature: 0.7

prompt:
  system: You are a helpful assitant.
  user: What is AI?

hydra:
  run:
    dir: geobias_logs
  sweep:
    dir: .

seed: 1
