# @package _global_

defaults:
  - _self_

data:
  populations: names.json
  examples: generated_examples.txt
  stereotypes: stereotype_dimensions_dictionary.csv

processing:
  max_examples: 5
  standardization: True

dimensions:
  stereotypes: [Sociability, Morality, Ability, Agency, Status, Politics, Religion]
  polar_labels: {
    Sociability: [Low sociability, High sociability],
    Morality: [Low morality, High morality],
    Ability: [Low ability, High ability],
    Agency: [Low agency, High agency],
    Status: [Low status, High status],
    Politics: [Progressive, Traditional],
    Religion: [Non-religious, Religious],
  }

embeddings_output_dir: embeddings
projections_output_dir: projections

model:
  name: google-bert/bert-base-uncased
  primer: ""
  primer_name: default

hydra:
  run:
    dir: geobias_logs
  sweep:
    dir: .